macros: fix expressions as formatting arguments
Due to missing block to convert arguments to an expression, the
following code was invalid:

    debug!(&ctx, "got {} bytes", (*skb).data_end - (*skb).data);

Failing to compile with the error:

    error[E0277]: cannot subtract `Result<usize, ()>` from `usize`

This is due to the argument being used as:

    match #arg.write(...) {

Which expands to:

    match (*skb).data_end - (*skb).data.write(...) {

Effectively trying to substract the result of `write` to our `data_end`.